"""AGENTS.md builder — Russian-language templates per project kind.

Plain string building, no template engine (zero dependencies). Every
kind gets: header, overview, setup, architecture tree, code style,
testing, common tasks, do-not list, log. Sections stay short — the
32 KiB cascade limit is real (agents.md / Codex cascade semantics).
"""

from __future__ import annotations

import datetime
from pathlib import Path

from ._version import __version__
from .structure import render_tree, src_dir
from .types import (
    KIND_1C_EDT,
    KIND_1C_XML,
    KIND_GENERIC,
    KIND_JS_TS,
    KIND_PYTHON,
    ProjectInfo,
)

AGENTS_FILENAME = "AGENTS.md"

_KIND_OVERVIEW = {
    KIND_1C_EDT: "Конфигурация 1С:Предприятие 8.3, разработка в 1C:EDT (формат исходников EDT, .mdo).",
    KIND_1C_XML: "Конфигурация 1С:Предприятие 8.3, исходники — XML-выгрузка Конфигуратора.",
    KIND_PYTHON: "Проект на Python.",
    KIND_JS_TS: "Проект на JavaScript/TypeScript.",
    KIND_GENERIC: "Проект без распознанного стека — заполните обзор вручную.",
}

_LINT_COMMANDS = {
    "ruff": "ruff check .",
    "black": "black .",
    "mypy": "mypy .",
    "eslint": "npx eslint .",
    "prettier": "npx prettier --check .",
}


def generate_agents_md(info: ProjectInfo, *, date: str | None = None) -> str:
    """Render the AGENTS.md text for a detected project."""

    today = date or datetime.date.today().isoformat()
    sections: list[str] = [
        _header(info, today),
        _overview(info),
        _setup(info),
        _architecture(info),
        _code_style(info),
        _testing(info),
        _common_tasks(info),
        _do_not(info),
        _log(today),
    ]
    return "\n\n".join(sections) + "\n"


def write_agents_md(root: Path, content: str) -> Path:
    """Write AGENTS.md into the project root; returns the path."""

    path = Path(root) / AGENTS_FILENAME
    path.write_text(content, encoding="utf-8")
    return path


# -- sections ---------------------------------------------------------------------


def _header(info: ProjectInfo, date: str) -> str:
    return (
        f"# AGENTS.md — {info.name}\n\n"
        f"> Auto-generated by agents-md v{__version__} | {date} | "
        f"{info.summary_line()}\n\n"
        "Правила проекта для AI-агентов и людей. Это черновик: проверь, "
        "поправь под реальность и закоммить."
    )


def _overview(info: ProjectInfo) -> str:
    overview = _KIND_OVERVIEW[info.kind]
    lines = [overview]
    if info.languages:
        lines.append(f"Языки/платформа: {', '.join(info.languages)}.")
    if info.description:
        lines.append(info.description)
    for note in info.notes:
        lines.append(f"- {note}")
    return "## Project Overview\n\n" + "\n".join(lines)


def _setup(info: ProjectInfo) -> str:
    if info.kind in (KIND_1C_EDT, KIND_1C_XML):
        return _setup_1c(info)
    if info.kind == KIND_PYTHON:
        return _setup_python(info)
    if info.kind == KIND_JS_TS:
        return _setup_js(info)
    return _setup_generic()


def _setup_1c(info: ProjectInfo) -> str:
    src = src_dir(info.root, info.kind)
    src_note = f"Исходники конфигурации: `{src.name}/`." if src else "Исходники конфигурации: см. структуру ниже."
    return f"""## Setup

### Prerequisites
- 1С:Предприятие 8.3.22+
- {'1C:EDT 2026.1+' if info.kind == KIND_1C_EDT else '1С:Конфигуратор'}
- Java 17+ и bsl-language-server.jar (статическая проверка BSL)

### Импорт конфигурации
- {'1C:EDT: File → Import → 1C:Enterprise Configuration → From file, выбрать `src/`' if info.kind == KIND_1C_EDT else 'Конфигуратор: Конфигурация → Загрузить конфигурацию из файлов'}
- {src_note}

### Статическая проверка (обязательно перед коммитом)
```bash
java -jar bsl-language-server.jar analyze src/ -r json
# или через пакет bsl-verify: bsl-check src/
```"""


def _setup_python(info: ProjectInfo) -> str:
    version = info.python_version or ">=3.10"
    return f"""## Setup

### Prerequisites
- Python {version}

### Install
```bash
python -m venv .venv
source .venv/bin/activate   # Windows: .venv\\Scripts\\activate
pip install -e .            # или: pip install -r requirements.txt
```

### Environment
- Секреты — только в переменных окружения; `.env` в `.gitignore`, шаблон в `.env.example`.
- Никаких ключей в коде, тестах и конфигах."""


def _setup_js(info: ProjectInfo) -> str:
    return """## Setup

### Prerequisites
- Node.js LTS

### Install
```bash
npm install
```

### Environment
- Секреты — только в переменных окружения (`.env` в `.gitignore`, шаблон в `.env.example`)."""


def _setup_generic() -> str:
    return """## Setup

- Опиши prerequisites и шаги установки вручную (стек не распознан).
- Секреты — только в переменных окружения; `.env` в `.gitignore`."""


def _architecture(info: ProjectInfo) -> str:
    tree = render_tree(info.name, info.structure)
    return f"## Architecture\n\n```text\n{tree}\n```"


def _code_style(info: ProjectInfo) -> str:
    lines = ["## Code Style\n"]
    if info.kind in (KIND_1C_EDT, KIND_1C_XML):
        lines += [
            "- Стандарт разработки: https://its.1c.ru/db/v8std",
            "- Именование: кириллица, ПаскальКейс (`СоздатьДокумент()`); синонимы — при необходимости",
            "- Комментарии методов: `// Параметры: ... Возвращаемое значение: ...`",
            "- Области кода: `#Область ... #КонецОбласти`",
            "- Запрещено: устаревшие методы (например, `Сообщить()`), латиница в идентификаторах",
        ]
    elif info.kind == KIND_PYTHON:
        lines += [
            "- Формат: ruff-совместимый, длина строки 100",
            "- Типизация: аннотации типов в публичных API",
            "- Docstrings: английские; сообщения и README: русские (или язык проекта)",
        ]
    elif info.kind == KIND_JS_TS:
        lines += [
            "- Строгий TypeScript (если tsconfig.json присутствует)",
            "- Формат и линтер: см. конфиги в корне",
        ]
    else:
        lines += ["- Опиши правила стиля вручную."]

    if info.linters:
        lines.append("- Инструменты: " + ", ".join(f"`{l}`" for l in info.linters))
        commands = [f"  {name}: `{cmd}`" for name, cmd in _LINT_COMMANDS.items()
                    if name in info.linters]
        if commands:
            lines.append("")
            lines.append("```bash")
            lines.extend(commands)
            lines.append("```")
    return "\n".join(lines)


def _testing(info: ProjectInfo) -> str:
    if info.kind in (KIND_1C_EDT, KIND_1C_XML):
        body = """- Vanessa Automation (BDD): сценарии в `features/` (если есть)
- xUnitFor1C: тесты в `tests/` (если есть)
- Статическая проверка BSL: `bsl-check src/` — должна быть зелёной перед коммитом"""
    elif info.test_runner:
        commands = {
            "pytest": "pytest -q",
            "vitest": "npx vitest run",
            "jest": "npx jest",
        }
        cmd = commands.get(info.test_runner)
        body = f"- Раннер: `{info.test_runner}`"
        if cmd:
            body += f"\n\n```bash\n{cmd}\n```"
    else:
        body = "- Тестовый раннер не обнаружен — опиши, как проверять изменения."
    return f"## Testing\n\n{body}"


def _common_tasks(info: ProjectInfo) -> str:
    if info.kind in (KIND_1C_EDT, KIND_1C_XML):
        return """## Common Tasks

### Новый справочник
1. Создай метаданные в `src/Catalogs/` (EDT: New → Catalog)
2. Реквизиты — во вкладке Attributes; табличные части — TabularSections
3. Модуль объекта `Ext/ObjectModule.bsl`, модуль менеджера `Ext/ManagerModule.bsl`
4. Проверка: `bsl-check src/` — без Error

### Новая внешняя обработка (EPF)
1. Создай в Конфигураторе → Внешние обработки
2. Исходники — в `external/epf/`
3. Модуль: BSL, кириллица, стандарты 1С

### Деплой
1. Разработка: обновление конфигурации БД из EDT/Конфигуратора
2. Прод: через CFE-расширение, после прогона регресса"""
    if info.kind == KIND_PYTHON:
        return """## Common Tasks

### Новая фича
1. Реализуй в исходниках
2. Юнит-тесты — рядом/в `tests/`, без сети в тестах
3. Прогони линтер и тесты, закоммить с внятным сообщением"""
    if info.kind == KIND_JS_TS:
        return """## Common Tasks

### Новая фича
1. Реализуй в исходниках
2. Тесты — рядом с кодом
3. Линтер + форматтер + тесты зелёные, потом коммит"""
    return """## Common Tasks

- Опиши типовые задачи проекта вручную."""


def _do_not(info: ProjectInfo) -> str:
    common = [
        "не коммить `.env` и любые секреты/токены",
        "не коммить артефакты сборки (`build/`, `dist/`, `__pycache__/` и т.п.)",
    ]
    if info.kind in (KIND_1C_EDT, KIND_1C_XML):
        specific = [
            "не изменяй основную конфигурацию напрямую в проде — только через расширения (CFE)",
            "не используй латиницу в идентификаторах — стандарты 1С требуют кириллицу",
            "не пропускай статическую проверку BSL перед коммитом",
        ]
    elif info.kind == KIND_PYTHON:
        specific = [
            "не оставляй `print()` в продовом коде — используй logging",
            "не хардкодь пути и секреты — настройки через env",
        ]
    else:
        specific = []
    items = specific + common
    return "## Do NOT\n\n" + "\n".join(f"- ❌ {item}" for item in items)


def _log(date: str) -> str:
    return f"## Log\n\n- {date}: AGENTS.md сгенерирован agents-md (проверь и отредактируй)"
